### ISSUE TITLE
Lock down color scheme

### ISSUE THREAD

**Issue by dreshfield** [somewhere-beer/somewhere.beer#1]
- [x] Create palette for choosing final color scheme (@cubtekki)
- [x] Generate palette combinations for group review (@cubtekki)
- [x] Decide on final palette (@cubtekki @dreshfield @lmodenbach @msbir @TLJessop)

**Comment by cubtekki** [comment]
- [ ] Create palette for choosing final color scheme (@cubtekki)
- [ ] Discuss as a group and decide on final palette (@dreshfield @msbir @TLJessop @lmodenbach)

**Comment by dreshfield** [comment]
Team voting selected palette 2 as our final choice.
