### ISSUE TITLE
Write short individual blurbs for About page

### ISSUE THREAD

**Issue by cubtekki** [somewhere-beer/somewhere.beer#9]
- [x] David
- [x] Jacob
- [x] Thomas
- [x] Maayan
- [x] Lisa

**Comment by dreshfield** [comment]
Think this could probably be in the neighborhood of 3-5 sentences -- not sure we need to get super in-depth here. Thoughts?

**Comment by dreshfield** [comment]
Closed by d4251cbc14dc0a1943337efc2545153e6bad5a95.
